steps:
  - command:
      - "swift package clean"
      - "swift build"
      - "swift test --enable-code-coverage"
  - command:
      - "cd Demo"
      - "xcodebuild -scheme 'SwiftNodeEditorDemoApp' -allowProvisioningUpdates -destination 'generic/platform=macOS'"
  - command:
      - "cd Demo"
      - "xcodebuild -scheme 'SwiftNodeEditorDemoApp' -allowProvisioningUpdates -destination 'generic/platform=iOS'"
  - command:
      - "swiftlint lint --quiet"
