steps:
  - commands:
      - "swift package clean"
      - "swift build"
      - "swift test --enable-code-coverage"
      - "cd Demo"
      - "xcodebuild -scheme 'SwiftNodeEditorDemo' -allowProvisioningUpdates -destination 'generic/platform=macOS'"
      - "xcodebuild -scheme 'SwiftNodeEditorDemo' -allowProvisioningUpdates -destination 'generic/platform=iOS'"
      - "swiftlint lint --quiet"
